#ifndef ANISTAIRS_SENSOR_TOP_TRIGGER_PIN
    #define ANISTAIRS_SENSOR_TOP_TRIGGER_PIN -1
#endif
#ifndef ANISTAIRS_SENSOR_TOP_ECHO_PIN
    #define ANISTAIRS_SENSOR_TOP_ECHO_PIN -1
#endif
#ifndef ANISTAIRS_SENSOR_TOP_TRIGGER_MIN_DISTANCE
    #define ANISTAIRS_SENSOR_TOP_TRIGGER_MIN_DISTANCE 30
#endif
#ifndef ANISTAIRS_SENSOR_TOP_TRIGGER_MAX_DISTANCE
    #define ANISTAIRS_SENSOR_TOP_TRIGGER_MAX_DISTANCE 50
#endif

#ifndef ANISTAIRS_SENSOR_BOTTOM_TRIGGER_PIN
    #define ANISTAIRS_SENSOR_BOTTOM_TRIGGER_PIN -1
#endif
#ifndef ANISTAIRS_SENSOR_BOTTOM_ECHO_PIN
    #define ANISTAIRS_SENSOR_BOTTOM_ECHO_PIN -1
#endif
#ifndef ANISTAIRS_SENSOR_BOTTOM_TRIGGER_MIN_DISTANCE
    #define ANISTAIRS_SENSOR_BOTTOM_TRIGGER_MIN_DISTANCE 30
#endif
#ifndef ANISTAIRS_SENSOR_BOTTOM_TRIGGER_MAX_DISTANCE
    #define ANISTAIRS_SENSOR_BOTTOM_TRIGGER_MAX_DISTANCE 50
#endif
#ifndef ANISTAIRS_TIME_BETWEEN_EACH_STEP_MS
    #define ANISTAIRS_TIME_BETWEEN_EACH_STEP_MS 150
#endif
#ifndef ANISTAIRS_TIME_THAT_EACH_STEP_STAYS_ON_MS
    #define ANISTAIRS_TIME_THAT_EACH_STEP_STAYS_ON_MS 1000
#endif
#ifndef ANISTAIRS_TRANSITION_TIME_MS
    #define ANISTAIRS_TRANSITION_TIME_MS 250
#endif
#ifndef ANISTAIRS_LEDS_PER_STEP
    #define ANISTAIRS_LEDS_PER_STEP "10;10;10;"
#endif