#ifndef USERMOD_ANIMATED_STAIRCASE_V2_TOP_SENSOR_PIN
    #define USERMOD_ANIMATED_STAIRCASE_V2_TOP_SENSOR_PIN 35
#endif

#ifndef USERMOD_ANIMATED_STAIRCASE_V2_BOTTOM_SENSOR_PIN
    #define USERMOD_ANIMATED_STAIRCASE_V2_BOTTOM_SENSOR_PIN 36
#endif

#ifndef USERMOD_ANIMATED_STAIRCASE_V2_TURN_STEPS_OF_AFTER_MS
    #define USERMOD_ANIMATED_STAIRCASE_V2_TURN_STEPS_OF_AFTER_MS 5000
#endif

#ifndef USERMOD_ANIMATED_STAIRCASE_V2_TIME_BETWEEN_EACH_STEP_MS
    #define USERMOD_ANIMATED_STAIRCASE_V2_TIME_BETWEEN_EACH_STEP_MS 250
#endif

#ifndef USERMOD_ANIMATED_STAIRCASE_V2_TRANSITION_TIME_MS
    #define USERMOD_ANIMATED_STAIRCASE_V2_TRANSITION_TIME_MS 250
#endif

#ifndef USERMOD_ANIMATED_STAIRCASE_V2_LEDS_PER_STEP
    #define USERMOD_ANIMATED_STAIRCASE_V2_LEDS_PER_STEP "10;10;10"
#endif

#define debugPrintDelay 0
#define TopMinDistance 20
#define TopMaxDistance 80
#define BottomMinDistance 20
#define BottomMaxDistance 80